# Generated by Django 5.2.4 on 2025-07-14 01:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
        ('subscription', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='user_subscription',
            field=models.ForeignKey(blank=True, help_text="Optional link to a user's subscription during the time of donation.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='subscription.usersubscription'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
    ]
