# Generated by Django 5.2.4 on 2025-07-14 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_donation_user_subscription_alter_donation_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user_subscription',
        ),
    ]
