# Generated by Django 5.2.4 on 2025-07-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0004_donation_is_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='donation',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=50),
        ),
    ]
