# Generated by Django 5.2.4 on 2025-07-19 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='mode',
            field=models.CharField(blank=True, choices=[('friend', 'Friend'), ('coach', 'Coach')], max_length=10, null=True),
        ),
    ]
