# Generated by Django 5.2.4 on 2025-07-14 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month for the earnings.', unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
            options={
                'verbose_name': 'Earning',
                'verbose_name_plural': 'Earnings',
                'ordering': ['month'],
            },
        ),
        migrations.CreateModel(
            name='SiteMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date for the recorded metrics.', unique=True)),
                ('views_count', models.PositiveIntegerField(default=0)),
                ('visits_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Site Metric',
                'verbose_name_plural': 'Site Metrics',
                'ordering': ['date'],
            },
        ),
    ]
